### ISSUE TITLE
Arreglar para que se vean los Docs

### ISSUE THREAD

**Issue by UO271245** [Arquisoft/radarin_es3a#112]
hacer que funcione https://radarines3awebapp.herokuapp.com/docs/

**Comment by Error404UsernameNotFound** [comment]
Inicialmente, el problema radicaba en que al desplegar en Heroku y tratar de acceder a la documentación, saltaba un mensaje de error de la API (un "Cannot GET /docs"). Pensé que habría algo mal redactado en la API, pero no me fijé en nada que pudiese causar el error, ni siquiera comparando el código con versiones anteriores en las que la documentación funcionaba, o con el trabajo de otros grupos.

Tras arreglar el problema de recarga de las páginas (reflejado en #119), el mensaje de error de la API desapareció, y la aplicación pasó a mostrar una plantilla básica al tratar de acceder a la documentación. Cabe decir que esto ya sucedía en local, antes de arreglar el problema de recarga de las páginas. 

Tras revisar esto, dirigí mi atención a los scripts del archivo "package.json" de "webapp", y concretamente al denominado "docs". 
![image](https://user-images.githubusercontent.com/60326859/116692274-62b66b00-a9bc-11eb-96a5-1e0e915ff7a3.png)
Como en alguna ocasión había dado problemas en el despliegue, probé a lanzarlo localmente. El error que saltó fue referente al paquete "asciidoctor-diagram", el cual no encontraba instalado entre las dependencias.
![image](https://user-images.githubusercontent.com/60326859/116692710-14ee3280-a9bd-11eb-9a94-ba803878e006.png)
Sin embargo, no existe módulo alguno en NPM de "asciidoctor-diagram", y en principio solo está disponible como una "gema" de Ruby. Tras revisar algo de documentación al respecto, me fijé en que este debería ser el caso también para el paquete "asciidoctor", a pesar de que ese sí que estaba instalado con NPM. De hecho, ninguno de los dos paquetes estaba instalado entre los "node-modules", ni en versiones anteriores del proyecto ni en los proyectos de otros compañeros. Lo curioso es que parece que se instaló en nuestro proyecto para solucionar el problema del despliegue en su momento. 

Tras esto, desinstalé completamente los paquetes de "asciidoctor" que había en el proyecto, devolviéndolo al estado de una versión desplegada pero con la documentación en marcha. Por supuesto, saltó otro error, esta vez indicando que el paquete "asciidoctor" no se encontraba instalado.
![image](https://user-images.githubusercontent.com/60326859/116693255-e9b81300-a9bd-11eb-9556-7025e5e0a321.png)
Siguiendo las instrucciones de uno de los README.ms de este proyecto (sección "webapp"), instalé Ruby en mi equipo, y traté de instalar manualmente los paquetes "asciidoctor" y "asciidoctor-diagram". Los errores del proyecto persisten a pesar de ello, aunque me resulta posible emplear el paquete "asciidoctor" para generar manualmente los .html a partir de los archivos de la documentación. No estoy seguro de cuál sería la posibilidad de, no pudiendo arreglar el problema del despliegue de la documentación, subir los .html generados manualmente (haciendo una ruta en la API para ello).

No he podido comprobar aún si la documentación funciona sin más con todos los paquetes eliminados de "node-modules", ya que tengo que lanzarla a "master" en un momento en que la aplicación tenga el deploy funcionando, y no quería molestar el trabajo de mis compañeros. Es lo siguiente que quiero comprobar. Sin embargo, si se me ha pasado algún detalle de la API o algún fragmento de código que pueda estar causando el problema, o si esto es un error reconocido que tenga una solución específica, soy todo oídos.

**Comment by Error404UsernameNotFound** [comment]
Una vez borradas las dependencias de "asciidoctor" que quedaban en el proyecto, probé a lanzar en "master" de nuevo la aplicación. El deploy funciona perfectamente bien en principio, pero en esta ocasión surge un problema con Heroku:
![image](https://user-images.githubusercontent.com/60326859/116787732-1a737780-aaa6-11eb-92ac-c987d3a7a39e.png)
![image](https://user-images.githubusercontent.com/60326859/116787739-2c551a80-aaa6-11eb-8404-2ee78b010939.png)

**Comment by pglez82** [comment]
Probasteis a ver si las imágenes de docker funcionan bien en local? Si borrais las dependencias del asciidoctor no tengo muy claro como puede el contenedor del webapp generar la documentación. Da la impresión que ahora está fallando `npm run docs`.

**Comment by Error404UsernameNotFound** [comment]
Para ser precisos, borré las dependencias de "asciidoctor" que no estaban en versiones anteriores de la aplicación; comparé la aplicación actual con una versión en la que el deploy Y su documentación funcionaban, y deje las referencias y módulos de NPM tal y como estaban en la misma. En principio en local el problema es el mismo, hasta donde he podido comprobar. Y sí, al ejecutar "nmp run docs" es cuando surgen los errores.

**Comment by UO271245** [comment]
Debido a la imposibilidad de arreglarlo para que funcionase con la automatizacion que proporciona asciidoctor y asciidiagram, hemos optado por generar nuestra propia documentacion mediante un componente de React.
