### ISSUE TITLE
Arreglar las relaciones de los diagramas del punto 6 de la documentacion

### ISSUE THREAD

**Issue by UO271245** [Arquisoft/radarin_es3a#30]
Cuidado si la relacion es al POD o el Server PODs.

**Comment by Error404UsernameNotFound** [comment]
¿Cuál sería exactamente la diferencia que debiera ser reflejada? A la hora de representar en los esquemas del apartado 6 la solicitud de X información a otros usuarios, información almacenada en Pods, no veo a priori la necesidad de redactar "Server Pod" frente a "Pod".

**Comment by UO271245** [comment]
Se podria especificar la inclusividad del POD en el Server de PODs mediante una relacion intermedia.
