### ISSUE TITLE
Arreglar el punto 6.2 de la documentacion

### ISSUE THREAD

**Issue by UO271245** [Arquisoft/radarin_es3a#33]
Los Friends Requests con el POD han de ser un proceso "asíncrono".( tomar decision arquitectónica en grupo.)

**Comment by Error404UsernameNotFound** [comment]
El punto 6.2 ha sido readaptado y completado con más información, cumpliendo el requisito planteado.

**Comment by uo264197** [comment]
Perfe
________________________________
De: Raúl Mínguez Rodríguez <notifications@github.com>
Enviado: lunes, 22 de febrero de 2021 17:02
Para: Arquisoft/radarin_es3a <radarin_es3a@noreply.github.com>
Cc: Juan Mencía Menéndez <UO264197@uniovi.es>; Assign <assign@noreply.github.com>
Asunto: Re: [Arquisoft/radarin_es3a] Arreglar el punto 6.2 de la documentacion (#33)


El punto 6.2 ha sido readaptado y completado con más información, cumpliendo el requisito planteado.
