### ISSUE TITLE
Debatir la utilizacion de una Base de Datos para guardar la informacion Basica

### ISSUE THREAD

**Issue by UO271245** [Arquisoft/radarin_es3a#44]
En ella tiene que poder guardarse los datos para el Log In

**Comment by UO271245** [comment]
Condicion para poder avanzar en la issue [https://github.com/Arquisoft/radarin_es3a/issues/41](https://github.com/Arquisoft/radarin_es3a/issues/41)

**Comment by Error404UsernameNotFound** [comment]
Quizá para apoyar el sistema de amigos podría emplearse una pequeña base de datos (que almacenase información muy básica sobre qué WebID's tiene un usuario agregados como amigos), para agilizar algunas operaciones; aunque tampoco la veo del todo necesaria. Referente al log in, ya que vamos a usar el WebID de cada usuario para acceder a la aplicación, a priori no considero necesario emplear ninguna base de datos adicional; si bien se puede tener en cuenta que, si un usuario tiene varios Pods en uso y por ende varios posibles WebID's, una cuenta de usuario almacenada en una base de datos permitiría asociar todos los WebID's a una única persona y trabajar con todos los datos en conjunto (además de que podríamos meter aquí el sistema de amigos, asociado a usuarios entre sí y no a WebID's). En cualquier caso, no considero estrictamente necesario el uso de bases de datos, si bien pueden ser útiles.

**Comment by uo271620** [comment]
Si se van a utilizar usuarios en nuestra aplicación relacionados a un POD con su información veo necesario el uso de una base de datos para guardar la información básica del usuario como son el nick que elija en Radarin, contraseña asociada y el WEBID que lo conectara con su POD de usuario, con ello evitaríamos tener que introducir nuestra WEBID siempre que quisiésemos utilizar la aplicación, además como usuario de un POD darás acceso a tus datos a la aplicación hasta que personalmente se lo niegues, es decir si para entrar en la aplicación solo hiciese falta un WEBID cualquiera que supiese nuestro WEBID podría hacerse pasar por nosotros, por ello veo necesaria la utilización de un usuario con contraseña que deberíamos guardar en alguna parte.

**Comment by UO271245** [comment]
Para realizar esta tarea propongo que o bien aprendamos a como utilizar MongoDB o utilizar HSQL para guardar unos datos minimos que conciernen a nuestra aplicación, ya que de la manera que plantea @Error404UsernameNotFound considero que habría un fallo de seguridad ya que te permitiría logearte con el WebID de un usuario que no fuese el tuyo propio.
Para solucionar este problema propongo guardar una tabla en la base de datos llamada User que tenga un campo ID, un campo Nick y finalmente un campo Password, con esta información no estariamos rompiendo ningun principio solid ya que en principio no es informacion personal del usuario y el POD seguiria teniendo la informacion que tiene el control el usuario.
Esto hace que haya que crear una especie de bandeja de entrada una vez te logueas en la aplicación en la que el usuario puede agregar los diferentes POD que requiera, desloguearse o acceder a ver el mapa.

**Comment by Error404UsernameNotFound** [comment]
@UO271245 @uo271620 referente al posible fallo de seguridad, por clarificar, no consideraba el log in de la aplicación empleando un "introducir WebID" de forma simple, tenía en cuenta algún método de validación que certificase que el usuario es el propietario de dicho WebID. Sin embargo, es cierto que la implementación de un sistema así sería más compleja que una base de datos, y ciertamente no tendríamos por qué estar rompiendo ningún principio de Solid si se lleva a cabo correctamente. Concuerdo con la idea de @UO271245 de implementar una sección donde agregar o quitar los diferentes WebID de los Pods de un usuario. Solo por plantearlo, ¿cómo almacenaríamos la información de los WebID de cada usuario? ¿Agregamos en esta misma base de datos los WebID asociados a cada persona?

**Comment by Error404UsernameNotFound** [comment]
Resultado del debate anotado en el [acta](https://github.com/Arquisoft/radarin_es3a/wiki/%5BReuni%C3%B3n-Equipo%5D-Acta-26_02_2021).
