### ISSUE TITLE
Informarse sobre MongoDB

### ISSUE THREAD

**Issue by UO271245** [Arquisoft/radarin_es3a#47]
Buscar informacion con respecto a las bases de datos no relacionales.
Crear el esquema de agrupaciones para los diferentes POD o identificadores de los mismos.

**Comment by UO258273** [comment]
@UO264545 y yo ya hemos comprendido como funcionan las bases de datos con mongoDB.
Procedemos a crear dos entradas de la wiki para explicar el funcionamiento de esta y como crear un cluster para almacenar en el la información deseada.
Estas dos entradas de la wiki serán utilizadas como base para explicar al resto de los integrantes del grupo el funcionamiento de esta base de datos.
