### ISSUE TITLE
Arreglar problema con herokuapp

### ISSUE THREAD

**Issue by UO258273** [Arquisoft/radarin_es3a#66]
Al llamar a la app de heroku para ver nuestra aplicación corriendo desde los servidores de GitHub, se sigue ejecutando la aplicación inicial dada por los profesores.
Tenemos la teoría de que al estar utilizando el paradigma de ejecución continua, hay que especificar explícitamente que el código a ejecutar ha cambiado.

**Comment by UO264545** [comment]
Una posible solución es comentar todos los tests.

**Comment by UO271245** [comment]
Cerrado por continuacion en el issue [83](https://github.com/Arquisoft/radarin_es3a/issues/83).
