### ISSUE TITLE
Decidir como gestionar las notificaciones de la aplicación en el movil

### ISSUE THREAD

**Issue by UO271245** [Arquisoft/radarin_es3a#70]

**Comment by UO258273** [comment]
Podíamos mirar un bot para Telegram, que mande las notificaciones de la app móvil a través de un bot

**Comment by UO271245** [comment]
En mi opinion hay dos tipos de soluciones para este problema:
1-Bot de Telegram
2-Aplicacion creada en android studio con navegador interno.

**Comment by UO271245** [comment]
Buscando informacion me he encontrado con esto para una vista previa a lo que tenemos que hacer:
[https://blog.logrocket.com/how-to-create-and-send-push-notifications-in-react-native/](https://blog.logrocket.com/how-to-create-and-send-push-notifications-in-react-native/)
