### ISSUE TITLE
Error en deploy-webapp

### ISSUE THREAD

**Issue by UO271245** [Arquisoft/radarin_es3a#74]
Tenemos un error en el deploy de webapp, hemos llegado a un punto muerto al ejecutar heroku deploy.

`deploy-webapp
Error: Command failed: heroku container:push web --app radarines3awebapp --arg API_URI="https://radarines3arestapi.herokuapp.com/api" The command '/bin/sh -c npm run docs' returned a non-zero code: 1 ▸ Error: docker build exited with Error: 1
`

**Comment by pglez82** [comment]
Yo en vuestro Github actions veo que ya falla a la hora de construir la webapp. No llega a los tests de integración y tampoco al despliegue. El problema que tenéis es un conflicto entre el package.json y el package-json.lock (podéis ver que falla al hacer npm ci). Tenéis que clonar el proyecto, hacer npm install (esto corregirá el conflicto), y subir al repositorio el nuevo package-lock.json. Este arreglará el error que tenéis ahora mismo en ese job, aunque no sé si hay más cosas mal.

Pablo

**Comment by uo271620** [comment]
Tras realizar añadir asciidoctor en package.json de web-app con el comando `npm install asciidoctor` el error fue solucionado
