### ISSUE TITLE
Error en e2e-tests 

### ISSUE THREAD

**Issue by UO271245** [Arquisoft/radarin_es3a#75]
En este error nos hemos visto en la obligacion de comentar los tests cambiandoles la extension para que se pudiese pasar del apartado del deploy e2e test. Si no los hubiesemos comentado nos daría el siguiente error:

`Run npm --prefix webapp run test:e2e

> webapp@0.1.0 test:e2e /home/runner/work/radarin_es3a/radarin_es3a/webapp
> cd e2e && jest

FAIL ../src/components/welcome/Welcome.test.js
  ● Test suite failed to run

    SyntaxError: /home/runner/work/radarin_es3a/radarin_es3a/webapp/src/components/welcome/Welcome.test.js: Support for the experimental syntax 'jsx' isn't currently enabled (24:25):

      22 |     it('renders the welcome message header1', () => {
      23 |         const renderer  = ShallowRenderer.createRenderer();
    > 24 |         renderer.render(<Welcome />);
         |                         ^
      25 |         const result = renderer.getRenderOutput();
      26 |         expect(result.type).toBe('div');
      27 | 

    Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
    If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.

      at Parser._raise (node_modules/@babel/parser/src/parser/error.js:60:45)
      at Parser.raiseWithData (node_modules/@babel/parser/src/parser/error.js:55:17)
      at Parser.expectOnePlugin (node_modules/@babel/parser/src/parser/util.js:157:18)
      at Parser.parseExprAtom (node_modules/@babel/parser/src/parser/expression.js:1153:18)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/src/parser/expression.js:565:23)
      at Parser.parseUpdate (node_modules/@babel/parser/src/parser/expression.js:545:21)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/src/parser/expression.js:529:17)
      at Parser.parseExprOps (node_modules/@babel/parser/src/parser/expression.js:349:23)
      at Parser.parseMaybeConditional (node_modules/@babel/parser/src/parser/expression.js:314:23)
      at Parser.parseMaybeAssign (node_modules/@babel/parser/src/parser/expression.js:269:21)`

**Comment by UO271245** [comment]
Para solucionar este error probamos diversas formas de hacer que reconociese la sintaxis experimental 'jsx':
Haciendo un rewired de la aplicación como explican en [https://stackoverflow.com/questions/62703393/support-for-the-experimental-jsx-isnt-currently-enabled](https://stackoverflow.com/questions/62703393/support-for-the-experimental-jsx-isnt-currently-enabled).
Intentamos añadir una configuración correcta de babel.
Intentamos comprender el error e informarnos sobre jest y como activar la traduccion de javascript a jxs.
Intentamos seguir los pasos que realizaban en este issue de github: [https://github.com/GeekyAnts/NativeBase/issues/3275](https://github.com/GeekyAnts/NativeBase/issues/3275)

Al no saber exactamente que es lo que estamos haciendo mal, nos dispusimos a crear este issue para pedir ayuda.

**Comment by pglez82** [comment]
Yo creo que es mejor que comentéis la parte de e2e en el github actions ya que hasta esta semana no se os hablará de tests e2e. De esta manera solo se necesitarán los tests unitarios para desplegar. Luego ya los meteréis cuando sepáis hacerlos.

Por otra parte, el error que os da es extraño porque los tests que se tienen que ejecutar cuando hacéis npm run test:e2e son los que están dentro de la carpeta e2e y no los otros, que son tests unitarios.

**Comment by UO258273** [comment]
Finalmente hemos conseguido arreglar el error
